export const data=[
    {
        name: "Springer Nature Computer Science (SNCS)",
        desc: "The Effect of Stopword Removal on Information Retrieval for Code-Mixed Data Obtained Via Social Media",
        
        authors: "Supriya Chanda, Sukomal Pal",
        year: "2023",
        link: "https://link.springer.com/article/10.1007/s42979-023-01942-7",
        bibtex: "@article{Chanda2023,\ndoi = {10.1007/s42979-023-01942-7},\nurl = {https://doi.org/10.1007/s42979-023-01942-7},\nyear = {2023},\nmonth = jun,\npublisher = {Springer Science and Business Media {LLC}},\nvolume = {4},\nnumber = {5},\nauthor = {Supriya Chanda and Sukomal Pal},\ntitle = {The Effect of Stopword Removal on Information Retrieval for Code-Mixed Data Obtained Via Social Media},\njournal = {{SN} Computer Science}\n}",
        
    },
    {
        name: "Forum for Information Retrieval Evaluation (Working Notes)(FIRE)",
        desc: "Coarse and Fine-Grained Conversational Hate Speech and Offensive Content Identification in Code-Mixed Languages using Fine-Tuned Multilingual Embedding",
        
        authors: "Supriya Chanda, Sacchit Sheth, Sukomal Pal",
        year: "2022",
        link: "https://ceur-ws.org/Vol-3395/T7-3.pdf",
        bibtex: "@inproceedings{Chanda2022CoarseAF,\n title={Coarse and Fine-Grained Conversational Hate Speech and Offensive Content Identification in Code-Mixed Languages using Fine-Tuned Multilingual Embedding},\n author={Supriya Chanda and Sacchit D. Sheth and Sukomal Pal},\n year={2022}}",
        // code: "",
        // shortform: "FIRE 2018",
    },
    {
        name: "Forum for Information Retrieval Evaluation (Working Notes)(FIRE)",
        desc: "Sentiment Analysis and Homophobia detection of Code-Mixed Dravidian Languages leveraging pre-trained model and word-level language tag",
        authors: "Supriya Chanda, Anshika Mishra, Sukomal Pal",
        year: "2022",
        link: "https://ceur-ws.org/Vol-3395/T2-12.pdf",
        bibtex: "@inproceedings{Chanda2022SentimentAA,\n title={Sentiment Analysis and Homophobia detection of Code-Mixed Dravidian Languages leveraging pre-trained model and word-level language tag},\n author={Supriya Chanda and Anshika Mishra and Sukomal Pal},\n year={2022}}",
        // code: "",
        // shortform: "FIRE 2018",
    },
    {
        name: "Forum for Information Retrieval Evaluation (Working Notes)(FIRE)",
        desc: "Is Meta Embedding better than pre-trained word embedding to perform Sentiment Analysis for Dravidian Languages in Code-Mixed Text?",
        authors: "Supriya Chanda, Rajat Pratap Singh, Sukomal Pal",
        year: "2021",
        link: "http://ceur-ws.org/Vol-3159/T6-20.pdf",
        bibtex: "@inproceedings{Chanda2021IsME,\ntitle={Is Meta Embedding Better than Pre-Trained Word Embedding to Perform Sentiment Analysis for Dravidian Languages in Code-Mixed Text?},\nauthor={Supriya Chanda and Rajat Singh and Sukomal Pal},\nbooktitle={Fire},\nyear={2021}}",
        // code: "",
        // shortform: "FIRE 2018",
    },
    {
        name: "Forum for Information Retrieval Evaluation (Working Notes)(FIRE)",
        desc:"Fine-tuning Pre-Trained Transformer based model for Hate Speech and Offensive Content Identification in English, Indo-Aryan and Code-Mixed (English-Hindi) languages",
         authors: "Supriya Chanda, Sundar Ujjwal, Shayak Das, Sukomal Pal",
        year: "2021",
        link: "http://ceur-ws.org/Vol-3159/T1-44.pdf",
        bibtex: "@inproceedings{Chanda2021FinetuningPT,\ntitle={Fine-tuning Pre-Trained Transformer based model for Hate Speech and Offensive Content Identification in English Indo-Aryan and Code-Mixed (English-Hindi) languages},\nauthor={Supriya Chanda and S. Ujjwal and Shayak Das and Sukomal Pal},\nbooktitle={Fire},\nyear={2021}}",
        // code: "",
        // shortform: "FIRE 2018",
    },
    {
        name: "Proceedings of the Fourteenth Workshop on Semantic Evaluation, 2012-2016",
        desc:"IRlab@ IITV at SemEval-2020 Task 12: Multilingual Offensive Language Identification in Social Media Using SVM",
         authors: "Anita Saroj, Supriya Chanda, Sukomal Pal",
        year: "2020",
        link: "https://aclanthology.org/2020.semeval-1.265.pdf",
        bibtex: "@inproceedings{Saroj2020IRlabIITVAS,\ntitle={IRlab@IITV at SemEval-2020 Task 12: Multilingual Offensive Language Identification in Social Media Using SVM},\nauthor={Anita Saroj and Supriya Chanda and Sukomal Pal},\nbooktitle={International Workshop on Semantic Evaluation},\nyear={2020}}",
        // shortform: "FIRE 2018",
    },
    {
        name: "Proceedings of the Sixth Workshop on Noisy User-generated Text (W-NUT 2020)",
        desc:"IRLab@ IITBHU at WNUT-2020 Task 2: Identification of informative COVID-19 English Tweets using BERT",
         authors: "Supriya Chanda, Eshita Nandy, Sukomal Pal",
        year: "2020",
        link: "https://aclanthology.org/2020.wnut-1.56.pdf",
        bibtex:"@inproceedings{Chanda2020IRLabIITBHUAW,\n    title={IRLab@IITBHU at WNUT-2020 Task 2: Identification of informative COVID-19 English Tweets using BERT},\n    author={Supriya Chanda and Eshita Nandy and Sukomal Pal},\n    booktitle={WNUT},\n    year={2020}\n  }"
        // shortform: "FIRE 2018",
    },
    {
        name: "Forum for Information Retrieval Evaluation (Working Notes)(FIRE), 535-540",
        desc:"IRLab@ IITBHU@ Dravidian-CodeMix-FIRE2020: Sentiment Analysis for Dravidian Languages in Code-Mixed Text.",
         authors: "S Chanda, S Pal",
        year: "2020",
        link: "https://ceur-ws.org/Vol-2826/T4-9.pdf",
        bibtex: "@inproceedings{Chanda2020IRLabIITBHUDravidianCodeMixFIRE2020,\n   title={IRLab@IITBHU@Dravidian-CodeMix-FIRE2020: Sentiment Analysis for Dravidian Languages in Code-Mixed Text},\n   author={Supriya Chanda and Sukomal Pal},\n   booktitle={Fire},\n   year={2020}\n }",
        // shortform: "FIRE 2018",
    },

]
